website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Note
from . import db

views = Blueprint('views', __name__)

todos = [{"task": "Sample Todo","done": False}]


@views.route('/')
@login_required
def home():
    return render_template("home.html", todos=todos, user=current_user)

@views.route("/add", methods=["POST"])
def add():
  todo = request.form['todo']
  todos.append({"task": todo, "done":False})
  return redirect(url_for("views.home"))

@views.route("/edit/<int:home>", methods=["GET", "POST"])
def edit(home):
  todo = todos[home]
  if request.method == "POST":
    todo['task'] = request.form["todo"]
    return redirect(url_for("views.home"))
  else:
    return render_template("edit.html", todo=todo, index=home)
  

@views.route("/check/<int:home>")
def check(home):
  todos[home]['done'] = not todos[home]['done']
  return redirect(url_for("views.home"))

@views.route("/delete/<int:home>")
def delete(home):
  del todos[home]
  return redirect(url_for("views.home"))




website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body style="background-color: wheat;">
    <nav class="navbar navbar-expand-lg " style="background-color: #eea990; font-size: 24px; font-family: Comic Sans MS, Comic Sans, cursive;">
        <button class="navbar-toggler" type="button" data-toggle="collapse"  data-target="#navbar">
            <span class="navbar-toggler-icon" style="background-color: aliceblue;"></span>
        </button>
        <div class="collapse navbar-collapse"   id="navbar">
          <div class="navbar-nav" >
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" style="color: white; padding-left: 30px;" id="home"  href="/">Home</a>
            <a class="nav-item nav-link" style="color: white; padding-left: 30px;" id="logout"  href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" style="color: white; padding-left: 30px;" id="login"  href="/login">Login</a>
            <a class="nav-item nav-link" style="color: white; padding-left: 30px;" id="signUp"  href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
  
      <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
      
    ></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
</body>
</html>

website/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{{ url_for('views.edit', home=index) }}" method="post">
        <input type="text" name="todo" value="{{ todo['task'] }}">
        <button type="submit">Save</button>

    </form>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}{% block content %}
<h1 style="text-align: center; padding-top: 20px; font-size: 50px; color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive;">Your Tasks</h1>
<form action="{{ url_for('views.add') }}" method="post" style="padding-top: 20px;">
    <input type="text" name="todo" >
    <button type="submit" style="background-color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive; color: white;">Add Task</button>
  </form>


<ul style="padding-top: 10px;">
    {% for todo in todos %}
    <li style="margin: 20px 20px; "> 
        <input type="checkbox" name="done" {% if todo['done'] %} checked {%endif%} disabled onchange="this.form.submit()">
        <span {%if todo['done'] %} style="text-decoration: line-through" {%endif%}>{{ todo['task'] }}</span>
        <a class=" mini ui yellow button "  href="{{ url_for('views.check', home=loop.index0) }}" style="background-color: #a39193; font-family: Comic Sans MS, Comic Sans, cursive ;">Check</a>
        <a class="mini ui olive button" href="{{ url_for('views.edit', home=loop.index0) }}" style="background-color: #eea990; font-family: Comic Sans MS, Comic Sans, cursive;">Edit</a>
        <a class="mini ui red button" href="{{ url_for('views.delete', home=loop.index0) }}" style="background-color: #aa6f73; font-family: Comic Sans MS, Comic Sans, cursive;">Delete</a>

    </li>
    {% endfor %}
</ul>
  
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="  mt-3 text-center" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive; font-size: 50px; padding-top: 20px;"> Welcome Back!!!</h1>
      </div>
      <div class="col-md-4  mx-auto col-10 col-md-8 col-lg-4 mt-5 ">
        <div class="card" style="background-color: wheat;">
          <div class="card-body">
            <form class="form" method="post">
              <label style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive ;">Email</label><br>
              <input type="email" class="form-control" name="email"><br>
              <label style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive;">Password</label><br>
              <input type="password" class="form-control" name="password"><br><br>
              <input type="submit" class="btn  btn-block btn-lg" value="Login" style="background-color: rgb(247, 151, 117) ; font-family: Comic Sans MS, Comic Sans, cursive; color: white;"><br>
              </form>
            <p style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive;">Not A Member? <a href=http://127.0.0.1:5000/sign-up style="color: #dc3545;">Create Account</a></p>
      </div>
    </div>
  </div>
  {% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}{% block content %}
<title>login</title>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="  mt-3 text-center" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive; font-size: 50px; "> Hurry And Signup!!!</h1>
      </div>
      <div class="col-md-4  mx-auto col-10 col-md-8 col-lg-4 mt-5 ">
        <div class="card" style="background-color: wheat;">
          <div class="card-body">
            <form method="POST" class="form">
              <label for="email" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive ;">Email Adress</label><br>
              <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"><br>
              <label for="firstName" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive ;">First Name</label><br>
              <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name"><br>
              <label for="password1" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive ;">Password</label><br>
              <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"><br><br>
              <label for="password2" style="color: #66545e; font-family: Comic Sans MS, Comic Sans, cursive ;">Confirm Password</label><br>
              <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"><br><br>
              <input type="submit" class="btn btn-block btn-lg" value="sign-up" style="background-color: rgb(247, 151, 117) ; color: white; font-family: Comic Sans MS, Comic Sans, cursive;"><br>
            </form>
            <p style="color: #66545e;font-family:Comic Sans MS, Comic Sans, cursive;">Already A Member? <a href=http://127.0.0.1:5000/login  style="color: #dc3545;">Login</a></p>
        </div>
      </div>
    </div>
  </div>

      
  
</form>
{% endblock %}